server:
  port : 9090

spring:
  datasource :
    driver-class-name : com.mysql.cj.jdbc.Driver
    url : jdbc:mysql://47.102.219.1:3306/PDD?serverTimezone=Asia/Shanghai
    username : lzw
    password : 123
  redis:
    host: jnlzw.top
    port: 6379
    password: 123


mybatis :
  mapper-locations : classpath:mybatis/*.xml
  type-aliases-package : com.lzw.pdddao.entity
  configuration.map-underscore-to-camel-case : true


